local map = require("langmap").map
local yazi = require("yazi")

map("n", "<C-г>", "<C-u>")
map("n", "<C-в>", "<C-d>")
map("n", "<leader>w", ":write<CR>")
map("n", "<leader>q", ":quit<CR>")
map("i", "jk", "<Esc>")
map("n", "<Esc><Esc>", ":noh<CR>")

map("n", "<leader>y", yazi.open_cwd)
map("n", "<leader>.", yazi.open_file_dir)
map("n", "<leader>f", ":FzfLua files<CR>")
map("n", "<leader>F", function()
    local dir = vim.fn.expand("%:p:h")
    require("fzf-lua").files({ cwd = dir ~= "" and dir or vim.uv.cwd() })
end)
map("n", "<leader>/", ":FzfLua live_grep<CR>")
map("n", "<leader>b", ":FzfLua buffers<CR>")
map("n", "<leader>s", ":FzfLua lsp_document_symbols<CR>")
map("n", "<leader>r", ":FzfLua lsp_references<CR>")
map("n", "<leader>a", ":FzfLua lsp_code_actions<CR>")
map("n", "<leader>d", ":FzfLua lsp_document_diagnostics<CR>")
map("n", "<leader>D", ":FzfLua lsp_workspace_diagnostics<CR>")

map("n", "<leader>u", ":Undotree<CR>")
map("n", "gd", vim.lsp.buf.definition)

map("n", "<Tab>", ":bnext<CR>", { silent = true })
map("n", "<S-Tab>", ":bprevious<CR>", { silent = true })
map("n", "<leader><Tab>", ":bd<CR>")
map({ "n", "v" }, "j", "mode() ==# 'V' ? 'j' : (v:count == 0 ? 'gj' : 'j')", { expr = true })
map({ "n", "v" }, "k", "mode() ==# 'V' ? 'k' : (v:count == 0 ? 'gk' : 'k')", { expr = true })

map("n", "<C-h>", ":wincmd h<CR>", { silent = true })
map("n", "<C-j>", ":wincmd j<CR>", { silent = true })
map("n", "<C-k>", ":wincmd k<CR>", { silent = true })
map("n", "<C-l>", ":wincmd l<CR>", { silent = true })
