set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g focus-events on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g pane-border-lines heavy
set -g pane-border-style "fg=black bg=default bold"
set -g pane-active-border-style "fg=blue bg=default bold"
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bg=default bold"
set -g status-left "#S"
set -g status-right ""
set -g status-position top

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

unbind %
bind v split-window -h -c "#{pane_current_path}"

unbind '"'
bind "'" split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind H swap-pane -s '{left-of}'
bind J swap-pane -s '{down-of}'
bind K swap-pane -s '{up-of}'
bind L swap-pane -s '{right-of}'

bind -n M-S-H swap-pane -s '{left-of}'
bind -n M-S-J swap-pane -s '{down-of}'
bind -n M-S-K swap-pane -s '{up-of}'
bind -n M-S-L swap-pane -s '{right-of}'

unbind f
bind f display-popup -d "#{pane_current_path}"
