[theme]
dark = "stargazing_gallery_plaster_dark"
light = "stargazing_gallery_plaster_light"

[editor]
true-color = true
color-modes = true
scrolloff = 4
scroll-lines = 1
line-number = "relative"
mouse-yank-register = "+"
default-yank-register = "+"
cursorline = true
bufferline = "multiple"
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "position", "total-line-numbers"]
separator = "|"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
tab = ":bn"
S-tab = ":bp"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
C-r = ":reload"
C-S-r = ":config-reload"
w = "@miw"
W = "@miW"

i = "insert_mode"
I = "insert_at_line_start"
a = "append_mode"
A = "insert_at_line_end"
o = "open_below"
O = "open_above"
c = "change_selection"
A-c = "change_selection_noyank"

[keys.normal.space]
w = ":write"
q = ":quit"
d = ":bc"
p = ":lsp-workspace-command"
y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output env -u YAZI_CONFIG_HOME yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

i = "insert_mode"
I = "insert_at_line_start"
a = "append_mode"
A = "insert_at_line_end"
o = "open_below"
O = "open_above"
c = "change_selection"
A-c = "change_selection_noyank"

[keys.insert]
esc = "normal_mode"
j = { k = "normal_mode" }
