[theme]
dark = "stargazing_gallery_plaster_dark"
light = "stargazing_gallery_plaster_light"

[editor]
true-color = true
color-modes = true
scrolloff = 4
scroll-lines = 1
line-number = "relative"
mouse-yank-register = "+"
default-yank-register = "+"
cursorline = true
bufferline = "multiple"
trim-final-newlines = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "position", "total-line-numbers"]
separator = "|"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
tab = ":bn"
S-tab = ":bp"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
C-r = ":reload"
C-S-r = ":config-reload"

i = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_mode"]
I = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_at_line_start"]
a = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "append_mode"]
A = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_at_line_end"]
o = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "open_below"]
O = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "open_above"]
c = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "change_selection"]
A-c = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "change_selection_noyank"]

[keys.normal.space]
w = ":write"
q = ":quit"
d = ":bc"
y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output env -u YAZI_CONFIG_HOME yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

i = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_mode"]
I = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_at_line_start"]
a = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "append_mode"]
A = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "insert_at_line_end"]
o = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "open_below"]
O = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "open_above"]
c = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "change_selection"]
A-c = [":sh ~/.config/helix/input-source enter >/dev/null 2>&1", "change_selection_noyank"]

[keys.insert]
esc = [":sh ~/.config/helix/input-source leave >/dev/null 2>&1", "normal_mode"]
j = { k = [":sh ~/.config/helix/input-source leave >/dev/null 2>&1", "normal_mode"] }
