[language-server.typos-lsp]
command = "typos-lsp"

[[language]]
name = "markdown"
workspace-lsp-roots = ["."]
language-servers = ["markdown-oxide", "typos-lsp"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = false

[[language]]
name = "typst"
language-servers = ["tinymist"]
